#!/usr/bin/env bash

thesaurus(){
    local 'term';
    _args 'term';
    curl --silent "dict://dict.org/d:${term}:moby-thesaurus" | grep '^ ';
}

musicbrainz(){
    local entity query jqFilter limit offset format;
    _args entity query [jqFilter] [limit] [offset=0] [format='json'];
    local url="https://musicbrainz.org/ws/2/${entity}?query=${query}&limit=${limit}&offset=${offset}&fmt=${format}";
    echo "${url}";
    jq --raw-output "${jqFilter:=.}" <(curl -s "${url}");
}
# musicbrainz release-group arid:"a630b133-bcc4-4796-9a0e-685c68b1e6ab" '."release-groups"[].title'

redditDASH(){
    local 'postID'
    _args 'postID'
    jsonPath='.[].data.children[].data.secure_media.reddit_video.fallback_url'
    jq --raw-output "${jsonPath} | select(. != null)" <(curl --silent --location --user-agent "${_USERAGENT}" "https://www.reddit.com/${postID}.json");
}

weather(){
    # [wttr.in](https://github.com/chubin/wttr.in)
    local 'city';
    _args '[city=Geneve]';
    curl "wttr.in/${city}";
}
