#!/usr/bin/env bash

log.debug.filepath;

# [Linux and Unix xargs command tutorial with examples](https://shapeshed.com/unix-xargs/)
# [An Opinionated Guide to xargs](https://www.oilshell.org/blog/2021/08/xargs.html)

function apt.depends(){
    # [How can I determine why apt-get will install a package?](https://askubuntu.com/a/447972)
    # [How to check package dependencies with apt-rdepends](https://www.techrepublic.com/article/how-to-check-package-dependencies-with-apt-rdepends/)
    function.requires apt-rdepends && function.requires dot || return 1;
    local package;
    args package;
    mkdir --parents --verbose "${XDG_CONFIG_HOME}/apt/dependencies/";
    apt-rdepends --dotty "${package}" > "${XDG_CONFIG_HOME}/apt/dependencies/${package}.dot";
    dot -Tpng < "${XDG_CONFIG_HOME}/apt/dependencies/${package}.dot" > "${XDG_CONFIG_HOME}/apt/dependencies/${package}.png";
}

function apt.install.all(){
    # while read -r ppa; do sudo add-apt-repository --update --yes "${ppa%%#*}"; done < "${XDG_CONFIG_HOME}/apt/ppa"
    function.requires apt && function.requires gawk || return 1;
    awk '!/^#/ {print $1}' "${XDG_CONFIG_HOME}/apt/"{base,dependency,user} | xargs -- sudo apt install --yes;
}

function apt.search(){
    # [https://manpages.ubuntu.com/manpages/focal/man8/apt-cache.8.html]
    function.requires apt || return 1;
    local package;
    args package;
    apt search --names-only "${package}";
}

function apt.upgrade(){
    # https://manpages.ubuntu.com/manpages/xenial/man8/apt.8.html
    # https://manpages.ubuntu.com/manpages/focal/man8/apt-get.8.html
    function.requires apt || return 1;
    sudo apt update && sudo apt full-upgrade --yes && sudo apt autoremove && sudo apt autoclean;
    # sudo apt update && sudo apt upgrade --yes && sudo apt autoremove && sudo apt autoclean;
    # update        update is used to download package information from all configured sources.
    # upgrade       upgrade is used to install available upgrades of all packages currently installed on the system from the sources configured via sources.list(5).
    # full-upgrade  full-upgrade performs the function of upgrade but will remove currently installed packages if this is needed to upgrade the system as a whole.
    # dist-upgrade  dist-upgrade in addition to performing the function of upgrade, also intelligently handles changing dependencies with new versions of packages; apt-get has a "smart" conflict resolution system, and it will attempt to upgrade the most important packages at the expense of less important ones if necessary.
    # autoremove    autoremove is used to remove packages that were automatically installed to satisfy dependencies for other packages and are now no longer needed.
    # autoclean     Like clean, autoclean clears out the local repository of retrieved package files. The difference is that it only removes package files that can no longer be downloaded, and are largely useless.
    # --yes         Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively.
}

function apt.upgrade.randomized(){
    (( RANDOM % 997 )) || apt.upgrade;
}

function apt.unstable(){
    # [DebianUnstable](https://wiki.debian.org/DebianUnstable)
    # [Configuring Apt Sources](https://wiki.debian.org/SourcesList#Examplesrcs.list)
    local url='http://deb.debian.org/debian/';
    printf '%s\n%s' "deb ${url} unstable main" "deb-src ${url} unstable main" | sudo tee '/etc/apt/sources.list';
}
