#!/usr/bin/env bash

log.debug.filepath;

# [Linux and Unix xargs command tutorial with examples](https://shapeshed.com/unix-xargs/)
# [An Opinionated Guide to xargs](https://www.oilshell.org/blog/2021/08/xargs.html)

function apt.depends(){
    # [How can I determine why apt-get will install a package?](https://askubuntu.com/a/447972)
    # [How to check package dependencies with apt-rdepends](https://www.techrepublic.com/article/how-to-check-package-dependencies-with-apt-rdepends/)
    function.requires apt-rdepends && function.requires dot || return 1;
    local package;
    args package;
    mkdir --parents --verbose "${XDG_CONFIG_HOME}/apt/dependencies/";
    apt-rdepends --dotty "${package}" > "${XDG_CONFIG_HOME}/apt/dependencies/${package}.dot";
    dot -Tpng < "${XDG_CONFIG_HOME}/apt/dependencies/${package}.dot" > "${XDG_CONFIG_HOME}/apt/dependencies/${package}.png";
}

function apt.install.all(){
    # while read -r ppa; do sudo add-apt-repository --update --yes "${ppa%%#*}"; done < "${XDG_CONFIG_HOME}/apt/ppa"
    function.requires apt && function.requires gawk || return 1;
    awk '!/^#/ {print $1}' "${XDG_CONFIG_HOME}/apt/"{base,dependency,user} | xargs -- sudo apt install --yes;
}

function apt.search(){
    # [https://manpages.ubuntu.com/manpages/focal/man8/apt-cache.8.html]
    function.requires apt || return 1;
    local package;
    args package;
    apt search --names-only "${package}";
}

function apt.upgrade(){
    function.requires apt || return 1;
    sudo apt update && sudo apt full-upgrade --auto-remove --purge --yes && sudo apt autoclean;
}

function apt.upgrade.randomized(){
    (( RANDOM % 997 )) || apt.upgrade;
}

function apt.unstable(){
    # [DebianUnstable](https://wiki.debian.org/DebianUnstable)
    # [Configuring Apt Sources](https://wiki.debian.org/SourcesList#Examplesrcs.list)
    local url='http://deb.debian.org/debian/';
    printf '%s\n%s' "deb ${url} unstable main" "deb-src ${url} unstable main" | sudo tee '/etc/apt/sources.list';
}
