#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

bareShell(){
    # [https://wiki.bash-hackers.org/scripting/bashbehaviour] [https://stackoverflow.com/a/21391035]
    env --ignore-environment bash --noprofile --norc;
    # --ignore-environment  start with an empty environment
    # --noprofile           Do not read either the system-wide startup file /etc/profile or any of the personal initialization files ~/.bash_profile, ~/.bash_login, or ~/.profile
    # --norc                Do not read and execute the system wide initialization file /etc/bash.bashrc and the personal initialization file ~/.bashrc if the shell is interactive
}

inspectDefinedFunctions(){
    # [https://wiki.bash-hackers.org/commands/builtin/declare#options]
    declare -f;
}

inspectDefinedFunctionNames(){
    # [https://wiki.bash-hackers.org/commands/builtin/declare#options]
    declare -F | cut --delimiter=' ' --fields=3;
}

inspectDefinedVariables()(
    # [list all variables declared in the current shell, and their values](https://stackoverflow.com/a/1305273/13019084)
    set -o posix;
    set;
)

inspectFunction(){
    # [How can I find where certain bash function is defined?](https://askubuntu.com/a/1146305)
    local 'function';
    _args 'function';
    shopt -s extdebug;
    declare -F "${function}";
    shopt -u extdebug;
    declare -f "${function}";
}

inspectInvokedCommands(){
    # [https://unix.stackexchange.com/a/631291]
    bash -l -i -x -c exit 2>&1;
    # -l                    Make bash act as if it had been invoked as a login shell
    # -i                    If the -i option is present, the shell is interactive
    # -x                    Print commands and their arguments as they are executed
    # -c                    If the -c option is present, then commands are read from the first non-option argument command_string
}

inspectInvokedFiles(){
    # [list files which the shell opened or tried to open](https://unix.stackexchange.com/a/334389)
    strace bash -l -i -x -c exit 2>&1 | grep "^openat";
    # -l                    Make bash act as if it had been invoked as a login shell
    # -i                    If the -i option is present, the shell is interactive
    # -x                    Print commands and their arguments as they are executed
    # -c                    If the -c option is present, then commands are read from the first non-option argument command_string
}
