#!/usr/bin/env bash

log.debug.filepath;

function docker.containerID(){
    function.requires docker || return 1;
    local image_name;
    args image_name;
    sudo docker ps --all --quiet --filter "ancestor=${image_name}"; # [How to filter docker process based on image](https://stackoverflow.com/a/33573321/13019084)
}

function docker.imageID(){
    function.requires docker || return 1;
    local image_name;
    args image_name;
    sudo docker images --quiet --filter "reference=${image_name}";
}

function docker.rm(){
    function.requires docker || return 1;
    local image_name container_ids;
    args image_name;
    container_ids=$(docker.containerID "${image_name}");
    if [[ -n "${container_ids}" ]]; then
        sudo docker stop "${container_ids}";
        sudo docker rm "${container_ids}";
    fi
}

function docker.rmi(){
    function.requires docker || return 1;
    local image_name image_id;
    args image_name;
    image_id=$(docker.imageID "${image_name}");
    docker.rm "${image_name}";
    sudo docker rmi "${image_id}";
}

function docker.runInteractive(){
    function.requires docker || return 1;
    local image_name container_name image_id;
    args image_name container_name;
    image_id=$(docker.imageID "${image_name}");
    sudo docker run --interactive --tty --name "${container_name}" "${image_id}" '/bin/bash';
}
