#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

export KRB5_CONFIG="${XDG_DATA_HOME}/krb/conf"; # [Main Kerberos configuration file.](https://web.mit.edu/kerberos/krb5-1.12/doc/admin/env_variables.html#environment-variables)
export KRB5_KTNAME="${XDG_DATA_HOME}/krb/keytab"; # [Default keytab file name.](https://web.mit.edu/kerberos/krb5-1.12/doc/admin/env_variables.html#environment-variables)
export KRB5_PRINCIPAL='adelanno@CERN.CH';

[[ ! -f "${KRB5_CONFIG}" ]] && curls 'http://linux.web.cern.ch/linux/docs/krb5.conf' "${KRB5_CONFIG}"

krb.encryptions(){
    klist -c -e | awk 'BEGIN{FS=":"}; /Etype/{gsub(/ /,""); print $NF}';
}

krb._keytabCreate(){
    # [https://twiki.cern.ch/twiki/bin/view/Main/Kerberos]
    # [https://gist.github.com/OmeGak/9530124]
    local encryptions;
    mkdir --verbose --parents "${KRB5_KTNAME%/*}";
    printf "%s\n" "running \`kinit ${KRB5_PRINCIPAL}\` to obtain encryption types..."; # [Kerberos ktutil, what kinds of encryption are available?](https://serverfault.com/a/620592)
    kinit "${KRB5_PRINCIPAL}" && IFS=, read -ra encryptions <<< "$(krbEncryptions)" || return 1
    printf "%s\n" 'Run the following commands in the `ktutil` prompt:';
    for encryption in "${encryptions[@]}"; do
        printf "%9s%s\n" '' "add_entry -password -p ${KRB5_PRINCIPAL} -k 1 -e ${encryption}";
    done
    printf "%9s%s\n" '' "write_kt ${KRB5_KTNAME}";
    printf "%9s%s\n" '' 'exit';
    ktutil && klist -t -e -K -k "${KRB5_KTNAME}"
}

krb.keytabCreate(){
    local password='pwdLOL';
    local encryptions;
    declare -a command;
    kinit "${KRB5_PRINCIPAL}" <<< "${password}" && IFS=, read -ra encryptions <<< "$(krbEncryptions)" || return 1
    for encryption in "${encryptions[@]}"; do
        command+=("add_entry -password -p ${KRB5_PRINCIPAL} -k 1 -e ${encryption}");
        command+=("${password}");
    done
    command+=("write_kt ${KRB_KTNAME}");
    command+=('exit')
    (printf "%s\n" "${command[@]}") | ktutil;
}

krb.keytabCERN(){
    ssh -t lxplus "/usr/sbin/cern-get-keytab --user ${KRB5_PRINCIPAL%@*} --keytab ~/keytab"
    scp lxplus:~/keytab "${KRB5_KTNAME}" && klist -t -e -K -k "${KRB5_KTNAME}"
}

krb(){
    # [https://linux.web.cern.ch/docs/kerberos-access/]
    # [https://uz.sns.it/~enrico/site/posts/kerberos/password-less-ssh-login-with-kerberos.html]
    (( "$(klist -k "${KRB5_KTNAME}" 2>/dev/null | grep --count "${KRB5_PRINCIPAL}")" == 0 )) && keytabCreate "${KRB5_PRINCIPAL}"
    [[ ! "$(pgrep --list-full k5start)" =~ ${KRB5_PRINCIPAL} ]] && k5start -v -b -K 10 -u "${KRB5_PRINCIPAL}" -f "${KRB5_KTNAME}"
}
