#!/usr/bin/env bash

log.debug.filepath;

# [Linux and Unix xargs command tutorial with examples](https://shapeshed.com/unix-xargs/)
# [An Opinionated Guide to xargs](https://www.oilshell.org/blog/2021/08/xargs.html)

function pip.config.list(){
    # https://pip.pypa.io/en/stable/cli/pip_config/
    pip config list
}

function pip.dependencies(){
    function.requires gawk || return 1;
    pip.show.all | awk 'BEGIN{FS=":"}; /Name:/{print $2} /Requires:/{print "    "$0} /Required-by:/{print "    "$0}'
}

function pip.inspect.packages(){
    # https://pip.pypa.io/en/stable/cli/pip_inspect/
    local fields='{name:.name, version:.version, summary:.summary[:200], keywords:.keywords, home_page:.home_page, requires:.requires_dist, provides:.provides_extra}'
    [[ -v VIRTUAL_ENV ]] && python3 -m pip inspect --local | jq ".installed[].metadata | ${fields}" | less
    python3 -m pip inspect --user | jq ".installed[].metadata | ${fields}" | less
}

function pip.install.user_packages(){
    # https://pip.pypa.io/en/stable/cli/pip_install/
    function.requires find && function.requires pip || return 1;
    pip.upgrade.packages "$(find "${XDG_CONFIG_HOME}/pip/user/" -maxdepth 1 -type f -not -name '.*' | xargs -- printf '--requirement="%s" ')";
    # python3 -m pip install --user --upgrade --upgrade-strategy='eager' "$(find "${XDG_CONFIG_HOME}/pip/user/" -maxdepth 1 -type f | xargs -- printf '--requirement="%s" ')";
}

function pip.list(){
    # https://pip.pypa.io/en/stable/cli/pip_list/
    function.requires pip || return 1;
    [[ -v VIRTUAL_ENV ]] && python3 -m pip list --local "$@" | grep --invert-match 'requires-python' && return 0;
    python3 -m pip list --user "$@" | grep --invert-match 'requires-python';
}

function pip.list.package_names(){
    # https://pip.pypa.io/en/stable/cli/pip_list/
    function.requires jq && pip.list --format='json' "$@" | jq --raw-output '.[].name' && return 0;
    function.requires gawk && pip.list "$@" | awk '(NR>2) {print $1}';
}

function pip.show.all(){
    # https://pip.pypa.io/en/stable/cli/pip_show/
    pip.list.package_names | xargs -- python3 -m pip show;
}

function pip.upgrade.packages(){
    # https://pip.pypa.io/en/stable/cli/pip_install/
    [[ -v VIRTUAL_ENV ]] && python3 -m pip install --upgrade "$@";
    python3 -m pip install --user --upgrade "$@";
}

function pip.upgrade.all_packages(){
    # https://pip.pypa.io/en/stable/cli/pip_install/
    pip.list.package_names | xargs -- pip.upgrade.packages;
    # python3 -m pip install --user --upgrade --upgrade-strategy='eager';
}

function pip.upgrade.outdated_packages(){
    # https://pip.pypa.io/en/stable/cli/pip_install/
    pip.list.package_names --outdated | xargs pip.upgrade.packages;
    # python3 -m pip list --user --outdated --format=json | jq --raw-output '.[].name' | xargs --max-lines=1 -- python3 -m pip install --user --upgrade --upgrade-strategy='eager';
}

function pypi.dependencies(){
    # [How to list dependencies for a python library without installing? [duplicate]](https://stackoverflow.com/a/50424967/13019084)
    function.requires jq && function.requires curl || return 1;
    local package;
    args package;
    jq --raw-output '.info.requires_dist[]' <(curl --silent "https://pypi.org/pypi/${package}/json");
}

function pypi.search(){
    # [JSON API for PyPi - how to list packages?](https://stackoverflow.com/a/74203841)
    # [Filter by Regex in JQ](https://stackoverflow.com/a/50868294)
    function.requires jq && function.requires curl || return 1;
    local package;
    args package;
    jq --raw-output ".projects[] | select(.name | test(\"^${package}\")).name" <(curl --silent --header 'Accept: application/vnd.pypi.simple.v1+json' 'https://pypi.org/simple/');
}
