#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

rustup(){
    local machine="$(uname --machine)"
    local kernel="$(uname --kernel-name)"
    local out_file="${XDG_DATA_HOME/share/bin}/rustup-init"
    wget "https://static.rust-lang.org/rustup/dist/${machine}-unknown-${kernel,,}-gnu/rustup-init" --output-document "${out_file}"
    [[ -f "${out_file}" ]] && chmod +x "${out_file}"
    export CARGO_HOME="${XDG_CACHE_HOME}/cargo" # [Cargo maintains a local cache of the registry index and of git checkouts of crates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables)
    export RUSTUP_HOME="${XDG_CONFIG_HOME}/rustup" # [RUSTUP_HOME (default: ~/.rustup or %USERPROFILE%/.rustup) Sets the root rustup folder, used for storing installed toolchains and configuration options.](https://rust-lang.github.io/rustup/environment-variables.html#environment-variables)
    rustup-init
}

rust.upgrade(){
    # awk '!/^#/ {print $1}' "${XDG_CONFIG_HOME}/rust/cargo" | xargs --replace={} -- echo --package {} | xargs -- cargo update
    awk '!/^#/ {print $1}' "${XDG_CONFIG_HOME}/rust/cargo" | xargs --max-lines=1 -- cargo update --package
}
