#!/usr/bin/env bash

log.debug.filepath;

rustup.install(){
    function.requires wget || return 1;
    local machine="$(uname --machine)";
    local kernel="$(uname --kernel-name)";
    local out_file="${XDG_DATA_HOME/share/bin}/rustup-init";
    local url="https://static.rust-lang.org/rustup/dist/${machine}-unknown-${kernel,,}-gnu/rustup-init";
    wget "${url}" --output-document "${out_file}";
    [[ -f "${out_file}" ]] && chmod +x "${out_file}";
    export CARGO_HOME="${XDG_CACHE_HOME}/cargo"; # [Cargo maintains a local cache of the registry index and of git checkouts of crates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables)
    export RUSTUP_HOME="${XDG_CONFIG_HOME}/rustup"; # [RUSTUP_HOME (default: ~/.rustup or %USERPROFILE%/.rustup) Sets the root rustup folder, used for storing installed toolchains and configuration options.](https://rust-lang.github.io/rustup/environment-variables.html#environment-variables)
    rustup-init;
}

cargo.upgrade(){
    function.requires gawk || return 1;
    execute.line_by_line 'cargo update --package' "${XDG_CONFIG_HOME}/rust/cargo";
}
