#!/usr/bin/env bash

log.debug.filepath;

function timer(){
    local time fractional;
    args time;
    fractional=$(bc <<< "${time} - ${time}/1"); # amount after decimal point, i.e. bc <<< $time/1 corresponds to int($time)
    sleep "${fractional}";
    time=$(bc <<< "${time}/1");
    for ((time="${time}"; time>0; time--)); do
        printf "${TXT[yellow]}%s\r${TXT[reset]}" "wait ${time} seconds...";
        sleep 1;
    done;
}

function sleep.random(){
    # [Bash: How to generate random float number using $RANDOM](https://unix.stackexchange.com/a/460470)
    local max_duration;
    args max_duration;
    range=$(bc <<< "32768/${max_duration}");
    duration=$(bc --mathlib <<< "scale=4; $RANDOM/${range}");
    # bc 'scale' parameter corresponds to precision (number of decimal places)
    # "$RANDOM" generates a number from 0 to 32767
    timer "${duration}";
}
