#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && shopt -q 'login_shell';
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

export EDITOR='/usr/bin/vim' # [The editor program called by sudoedit, vipw, and other such programs when you tell them to edit a file](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#EDITOR)
export VISUAL='/usr/bin/vim' # [This variable is used to specify the "visual" - screen-oriented - editor. Generally you will want to set it to the same value as the EDITOR variable](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#VISUAL)
export VIM="${XDG_CONFIG_HOME}/vim" # [The environment variable "$VIM" is used to locate various user files for Vim, such as the user startup script ".vimrc"](https://vimhelp.org/starting.txt.html#%24VIM)
export MYVIMRC="${VIM}/vimrc" # [The $MYVIMRC environment variable is set to the file that was first found, unless $MYVIMRC was already set and when using VIMINIT](https://vimhelp.org/starting.txt.html#%24MYVIMRC)
export VIMINIT="source ${MYVIMRC}" # [The value of $VIMINIT is used as an Ex command line](https://vimhelp.org/starting.txt.html#VIMINIT)

# `alias less`
export LESS='--ignore-case --LINE-NUMBERS --raw-control-chars --squeeze-blank-lines --status-column' # [https://man7.org/linux/man-pages/man1/less.1.html#ENVIRONMENT_VARIABLES] [https://man7.org/linux/man-pages/man1/less.1.html#OPTIONS]
export LESSKEY="${XDG_CONFIG_HOME}/less/key" # [Lesskey is used to specify a set of key bindings to be used by less](https://man7.org/linux/man-pages/man1/lesskey.1.html)
export PAGER='/usr/bin/less' # [The pager called by man and other such programs when you tell them to view a file](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#PAGER)
[[ ! -f ${LESSKEY} ]] && [[ -f "${XDG_CONFIG_HOME}/less/key.txt" ]] && lesskey -o "${LESSKEY}" "${XDG_CONFIG_HOME}/less/key.txt" # [The input file is a text file which describes the key bindings](https://man7.org/linux/man-pages/man1/lesskey.1.html) [How to make lesskey terminal-independent?](https://unix.stackexchange.com/a/377221)
