#!/usr/bin/env bash

log.debug.filepath;

export EDITOR="$(command -v nvim || command -v vim)"; # [The editor program called by sudoedit, vipw, and other such programs when you tell them to edit a file](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#EDITOR)

export LESS='--quit-if-one-screen --RAW-CONTROL-CHARS --LONG-PROMPT --window=-4 --ignore-case --no-histdups'; # [https://man7.org/linux/man-pages/man1/less.1.html#ENVIRONMENT_VARIABLES] [https://man7.org/linux/man-pages/man1/less.1.html#OPTIONS] [https://www.topbug.net/blog/2016/09/27/make-gnu-less-more-powerful/]

export PAGER="$(command -v bat || command -v less)"; # [The pager called by man and other such programs when you tell them to view a file](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#PAGER)

export VIM="${XDG_CONFIG_HOME}/vim"; # [The environment variable "$VIM" is used to locate various user files for Vim, such as the user startup script ".vimrc"](https://vimhelp.org/starting.txt.html#%24VIM)
export MYVIMRC="${VIM}/vimrc"; # [The $MYVIMRC environment variable is set to the file that was first found, unless $MYVIMRC was already set and when using VIMINIT](https://vimhelp.org/starting.txt.html#%24MYVIMRC)
export VIMINIT="source ${MYVIMRC}"; # [The value of $VIMINIT is used as an Ex command line](https://vimhelp.org/starting.txt.html#VIMINIT)

export VISUAL="${EDITOR}"; # [This variable is used to specify the "visual" - screen-oriented - editor. Generally you will want to set it to the same value as the EDITOR variable](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#VISUAL)
