#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && shopt -q 'login_shell';
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

export HISTFILE="${XDG_DATA_HOME}/bash/${HOSTNAME}.history" # [The name of the file in which command history is saved](https://wiki.bash-hackers.org/syntax/shellvars#histfile)
export HISTFILEBKP="${HISTFILE%/*}}/${HOSTNAME}.bkp.history"
export LESSHISTFILE="${XDG_DATA_HOME}/less/${HOSTNAME}.history" # [Name of the history file used to remember search commands and shell commands between invocations of less](https://man7.org/linux/man-pages/man1/less.1.html#ENVIRONMENT_VARIABLES)
export PYHISTFILE="${XDG_DATA_HOME}/python/${HOSTNAME}.history" # See `historyFile()` in `$PYTHONSTARTUP`
export PYHISTFILEBKP="${PYHISTFILE%/*}}/${HOSTNAME}.bkp.history"

# [Using History Interactively](https://www.gnu.org/software/bash/manual/html_node/Using-History-Interactively.html)
# [How can I avoid losing any history lines?](http://mywiki.wooledge.org/BashFAQ/088)
# Setting the HISTFILESIZE and HISTSIZE variables to an empty string makes the bash history size unlimited [https://www.soberkoder.com/unlimited-bash-history/] [https://stackoverflow.com/a/12234989/13019084] [https://resonantecho.net/linux/bash/2018/02/19/unlimited-bash-history.html]
export HISTCONTROL=ignoredups # [A colon-separated list of values controlling how commands are saved on the history list](https://wiki.bash-hackers.org/syntax/shellvars#histcontrol)
export HISTFILESIZE='' # [The maximum number of lines contained in the history file](https://wiki.bash-hackers.org/syntax/shellvars#histfilesize)
export HISTSIZE='' # [The number of commands to remember in the command history](https://wiki.bash-hackers.org/syntax/shellvars#histsize)
export HISTTIMEFORMAT='[%Y%m%d-%H%M%S] ' # [If this variable is set and not null, its value is used as a format string for strftime(3) to print the time stamp associated with each history entry displayed by the history builtin](https://wiki.bash-hackers.org/syntax/shellvars#histtimeformat)
export LESSHISTSIZE='' # [The maximum number of commands to save in the history file](https://man7.org/linux/man-pages/man1/less.1.html#ENVIRONMENT_VARIABLES)
shopt -s histappend # [If set, the history list is appended to the file named by the value of the HISTFILE variable when the shell exits, rather than overwriting the file](https://wiki.bash-hackers.org/internals/shell_options#histappend)
