#!/usr/bin/env bash

(( "${_VERBOSE}" >= 2 )) && [[ -n "${BASH}" ]] && shopt -q login_shell && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***" || return

export BASHRC="${XDG_CONFIG_HOME}/bash/bashrc"
export CURLWO="[%{filename_effective}] [%{size_download} B] [%{time_total} s]\n" # [curl write out](https://everything.curl.dev/usingcurl/verbose/writeout)
export DISTROVERSION="$(source '/etc/os-release' 2>/dev/null && echo "${ID}${VERSION_ID}" || lsb_release --short --id --release 2>/dev/null | tr -d '\n ')" # [https://unix.stackexchange.com/a/6348] [https://unix.stackexchange.com/a/25131]
export DATEFORMAT='+%Y.%m.%d-%H.%M.%S.%3N'  # [strftime - format date and time](https://man7.org/linux/man-pages/man3/strftime.3.html) [Command to get time in milliseconds](https://stackoverflow.com/a/18704121)
export FZF_DEFAULT_COMMAND="find -type f -maxdepth 10 -not -path '*/\.git/*'" # [Default command to use when input is tty](https://github.com/junegunn/fzf#environment-variables)
export GITSTATUSPROMPT='true'
export RSYNCOF="%i %o %b/%7''l %B %L %C %n" # [rsync log format](https://man7.org/linux/man-pages/man5/rsyncd.conf.5.html#:~:text=log%20format)
export SSHCONFIG="${XDG_CONFIG_HOME}/ssh/config"
export USERAGENT="$( ((RANDOM % 997)) || yt-dlp --dump-user-agent 2>/dev/null)" # [Display the current browser identification](https://github.com/ytdl-org/youtube-dl#options)
export USERAGENT="${USERAGENT:-'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3685.1 Safari/537.36'}"
export VENV_HOME="${XDG_DATA_HOME}/venv"
