#!/usr/bin/env bash

(( "${_VERBOSE}" >= 2 )) && [[ -n "${BASH}" ]] && shopt -q login_shell && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***" || return

# [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)
# [XDG Base Directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

export XDG_CACHE_HOME="${HOME}/.cache" # contains user-specific non-essential data files
export XDG_CONFIG_DIRS='/etc/xdg' # preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME
export XDG_CONFIG_HOME="${HOME}/.config" # contains user-specific configuration files [$XDG_CONFIG_HOME is considered more important than any of the base directories defined by $XDG_CONFIG_DIRS]
export XDG_DATA_DIRS='/usr/local/share/:/usr/share/' # preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME
export XDG_DATA_HOME="${HOME}/.local/share" # contains user-specific data files [$XDG_DATA_HOME is considered more important than any of the base directories defined by $XDG_DATA_DIRS]
export XDG_STATE_HOME="${HOME}/.local/state" # contains user-specific state files that should persist between (application) restarts
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-"/tmp/${USER}/runtime"}" && mkdir --parents "${XDG_RUNTIME_DIR}" && chmod 700 "${XDG_RUNTIME_DIR}" # contains user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) # [Good default for XDG_RUNTIME_DIR?](https://serverfault.com/a/727994)
