#!/usr/bin/env bash

log.debug.filepath;

function prompt.git_status(){
    # BASH parser for `git status --porcelain=v2` [https://git-scm.com/docs/git-status#_porcelain_format_version_2]
    local git_status="$(${GIT_BIN} status --porcelain=v2 --branch --show-stash 2>/dev/null)";
    [[ -z "${git_status}" ]] && return 0;
    unset GS;
    declare -A -g GS; # [associative array requires BASH>=4.0](https://bash-hackers.docs.cern.ch/syntax/arrays#associative_bash_4)
    local line index work_tree;
    while IFS= read -r line; do # By default, read [removes] all leading and trailing whitespace characters [http://mywiki.wooledge.org/BashFAQ/001#Trimming]
        case "${line:0:2}" in
            '# ') prompt.git_status.branch "${line}";;
            '? ') (( GS['?']++ ));; # untracked
            '! ') (( GS['!']++ ));; # ignored
            '1 '|'2 '|'u ')
                # [https://git-scm.com/docs/git-status#_changed_tracked_entries]
                case "${line:0:1}" in
                    '1') (( GS['changed']++ ));;
                    '2') (( GS['renamed_copied']++ ));;
                    'u') (( GS['unmerged']++ ));;
                esac
                # [https://git-scm.com/docs/git-status#_short_format]
                index="${line:2:1}";
                work_tree="${line:3:1}";
                [[ "${index}" != '.' ]] && (( GS["${index^}"]++ )); # [${PARAMETER^}](https://bash-hackers.docs.cern.ch/syntax/pe#case_modification)
                [[ "${work_tree}" != '.' ]] && (( GS["${work_tree,}"]++ )); # [${parameter,}](https://bash-hackers.docs.cern.ch/syntax/pe#case_modification)
                ;;
        esac
    done <<< "${git_status}"
    prompt.git_status.ps1
}

function prompt.git_status.branch(){
    # [https://git-scm.com/docs/git-status#_branch_headers]
    local line="$1";
    case "${line}" in # [${PARAMETER#PATTERN}](https://bash-hackers.docs.cern.ch/syntax/pe#from_the_beginning)
        '# branch.oid'*) GS['oid']="${line#*'branch.oid '}";;
        '# branch.head'*) GS['head']="${line#*'branch.head '}";;
        '# branch.upstream'*) GS['upstream']="${line#*'branch.upstream '}";;
        '# branch.ab'*) prompt.git_status.ahead_behind "${line}";;
        '# stash'*) GS['stash']="${line#*'stash '}";; # [https://git-scm.com/docs/git-status#_stash_information]
    esac
}

function prompt.git_status.ahead_behind(){
    # [https://git-scm.com/docs/git-status#_branch_headers]
    local line="$1";
    local ab="${line#*'branch.ab '}";
    GS['-']="${ab#* -}";
    ab="${ab%% -*}"; # [${PARAMETER%%PATTERN}](https://bash-hackers.docs.cern.ch/syntax/pe#from_the_end)
    GS['+']="${ab#+}";
}

function prompt.git_status.ps1(){
    # [A:added, C:copied, D:deleted, M:modified, R:renamed, T:type_changed(symlink/submodule), U:unmerged](https://git-scm.com/docs/git-status#_output)
    local ps1 key;
    [[ "${GS[head]}" == '(detached)' ]] && ps1="${TXT[red]}" || ps1="${TXT[green]}";
    ps1+="${GS[head]}${TXT[reset]}@";
    [[ "${GS[oid]}" == '(initial)' ]] && ps1+="${TXT[yellow]}${GS[oid]}" || ps1+="${TXT[magenta]}${GS[oid]:0:7}";
    ps1+="${TXT[cyan]}↓${TXT[reset]}";
    [[ -n "${GS[upstream]}" ]] && ps1+=":${TXT[red]}${GS[upstream]}${TXT[cyan]}↑${TXT[reset]}";
    for key in '+' '-'; do (( "${GS[${key}]:-0}" > 0 )) && ps1+=":${TXT[RED]}${GS[${key}]}${key^^}${TXT[reset]}"; done;
    for key in 'A' 'C' 'D' 'M' 'R' 'T' 'U'; do [[ -n "${GS[${key}]}" ]] && ps1+=":${TXT[yellow]}${GS[${key}]}${key}${TXT[reset]}"; done;
    for key in 'a' 'c' 'd' 'm' 'r' 't' 'u'; do [[ -n "${GS[${key}]}" ]] && ps1+=":${TXT[RED]}${GS[${key}]}${key^^}${TXT[reset]}"; done;
    for key in '?' '!'; do [[ -n "${GS[${key}]}" ]] && ps1+=":${TXT[yellow]}${GS[${key}]}${key}${TXT[reset]}"; done;
    printf "%s\n" "${ps1}";
}

function prompt.git_status.v1(){
    # [https://git-scm.com/docs/git-status#_porcelain_format_version_1]
    local git_status="$(${GIT_BIN} status --porcelain --branch --show-stash 2>/dev/null)";
    [[ -z "${git_status}" ]] && return 0;
    unset GS;
    declare -A -g GS; # [associative array requires BASH>=4.0](https://bash-hackers.docs.cern.ch/syntax/arrays#associative_bash_4)
    local line index work_tree;
    while IFS= read -r line; do # By default, read [removes] all leading and trailing whitespace characters [http://mywiki.wooledge.org/BashFAQ/001#Trimming]
        case "${line:0:2}" in
            '##') prompt.git_status.v1.branch "${line}";;
            '??') (( GS['?']++ ));; # untracked
            '!!') (( GS['!']++ ));; # ignored
            *) # [https://git-scm.com/docs/git-status#_short_format]
                index="${line:0:1}";
                work_tree="${line:1:1}";
                [[ "${index}" != ' ' ]] && (( GS["${index^}"]++ )); # [${PARAMETER^}](https://bash-hackers.docs.cern.ch/syntax/pe#case_modification)
                [[ "${work_tree}" != ' ' ]] && (( GS["${work_tree,}"]++ )); # [${parameter,}](https://bash-hackers.docs.cern.ch/syntax/pe#case_modification)
                ;;
        esac
    done <<< "${git_status}"
    prompt.git_status.ps1
}

function prompt.git_status.v1.branch(){
    local line="$1"
    local branch ab;
    read -r _ branch ab <<< "${line}";
    GS['oid']="$(git rev-parse --short HEAD 2>&1)";
    [[ ! "${branch}" =~ ... ]] && GS['head']="${branch}" || IFS=: read -r GS['head'] GS['upstream'] <<< "${branch/.../:}";
    [[ "${ab}" =~ 'ahead '([0-9]+) ]] && GS[+]="${BASH_REMATCH[1]}";
    [[ "${ab}" =~ 'behind '([0-9]+) ]] && GS[-]="${BASH_REMATCH[1]}";
}
