#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

_histBkpAppend(){
    if [[ ! -f "${_HISTFILEBKP}" ]]; then
        cp --interactive --verbose "${HISTFILE}" "${_HISTFILEBKP}" 2>/dev/null
    else
        local prevHistBufferEntry="$(fc -l -n -1 | sed 's|^[[:space:]]*||')" # [https://unix.stackexchange.com/a/38075] [https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html]
        [[ "${prevHistBufferEntry}" != "$(tail -1 "${_HISTFILEBKP}")" ]] && printf "#%s\n%s\n" "$(date +%s)" "${prevHistBufferEntry}" >> "${_HISTFILEBKP}" # poor man's implementation of `HISTCONTROL=ignoredups` for `${_HISTFILEBKP}`
    fi
}

_pyHistBkpCopy(){
    [[ ! -f "${_PYHISTFILEBKP}" ]] && cp --interactive --verbose "${_PYHISTFILE}" "${_PYHISTFILEBKP}" 2>/dev/null # see `historyFileBkp()` in `$PYTHONSTARTUP`
}

_historyPrompt(){
    # [Bash History Builtins](https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html)
    # [How can I avoid losing any history lines?](http://mywiki.wooledge.org/BashFAQ/088)
    history -a # Append the new history lines to the history file. These are history lines entered since the beginning of the current Bash session, but not already appended to the history file.
    _histBkpAppend
    _pyHistBkpCopy
}
