[/]
alttab-switcher-delay=100
alttab-switcher-style='icons+thumbnails'
desklet-snap-interval=25
enabled-applets=['panel1:left:0:menu@cinnamon.org:0', 'panel1:left:1:separator@cinnamon.org:1', 'panel1:left:2:grouped-window-list@cinnamon.org:2', 'panel1:right:0:systray@cinnamon.org:3', 'panel1:right:1:xapp-status@cinnamon.org:4', 'panel1:right:2:notifications@cinnamon.org:5', 'panel1:right:3:printers@cinnamon.org:6', 'panel1:right:4:removable-drives@cinnamon.org:7', 'panel1:right:5:keyboard@cinnamon.org:8', 'panel1:right:6:favorites@cinnamon.org:9', 'panel1:right:7:network@cinnamon.org:10', 'panel1:right:8:sound@cinnamon.org:11', 'panel1:right:9:power@cinnamon.org:12', 'panel1:right:10:calendar@cinnamon.org:13', 'panel1:right:11:cornerbar@cinnamon.org:14']
enabled-desklets=@as []
hotcorner-layout=['expo:false:0', 'scale:false:0', 'scale:false:0', 'desktop:false:0']
next-applet-id=15
panel-zone-symbolic-icon-sizes='[{"panelId": 1, "left": 28, "center": 28, "right": 16}]'
panels-height=['1:40']
window-effect-speed=1

[cinnamon-session]
quit-time-delay=60

[desktop/a11y/keyboard]
bouncekeys-delay=300
mousekeys-accel-time=300
mousekeys-init-delay=300
mousekeys-max-speed=10
slowkeys-delay=300

[desktop/a11y/mouse]
dwell-threshold=10
dwell-time=1.2
secondary-click-time=1.2

[desktop/applications/calculator]
exec='gnome-calculator'

[desktop/applications/terminal]
exec='gnome-terminal'
exec-arg='--'

[desktop/background]
picture-options='zoom'
picture-uri='file:///usr/share/desktop-base/joy-theme/wallpaper/gnome-background.xml'

[desktop/background/slideshow]
delay=15
image-source='xml:///usr/share/gnome-background-properties/debian-joy.xml'

[desktop/interface]
clock-show-date=true
clock-show-seconds=true
cursor-blink-time=1200
cursor-size=24
gtk-theme='Adwaita-dark'
text-scaling-factor=1.0

[desktop/media-handling]
autorun-never=false
autorun-x-content-ignore=@as []
autorun-x-content-open-folder=@as []
autorun-x-content-start-app=@as []

[desktop/notifications]
notification-duration=4
remove-old=false

[desktop/peripherals/keyboard]
delay=uint32 500
repeat-interval=uint32 30

[desktop/peripherals/mouse]
double-click=400
drag-threshold=8
locate-pointer=false
middle-click-emulation=true
speed=0.0

[desktop/peripherals/touchpad]
click-method='fingers'
speed=0.39999999999999997

[desktop/screensaver]
date-format='%Y-%m-%d'
default-message='delannoy@cern.ch'
show-clock=true
time-format='%H:%M:%S'
use-custom-format=true

[desktop/sound]
event-sounds=false

[desktop/wm/preferences]
min-window-opacity=30

[launcher]
check-frequency=300
memory-limit=2048

[muffin]
draggable-border-width=10
workspace-cycle=true

[settings-daemon/peripherals/keyboard]
numlock-state='off'

[settings-daemon/plugins/power]
lid-close-ac-action='nothing'
lid-close-battery-action='nothing'
sleep-display-ac=1800
sleep-display-battery=600
sleep-inactive-ac-timeout=0
sleep-inactive-battery-timeout=0
