# set -g default-terminal 'tmux-256color' # https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal

# [Run command in tmux and update the status bar](https://stackoverflow.com/a/79744620/13019084)
set -g status-right "#(aklog)"
set -g status-interval 3600
