#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 2 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

_source "${XDG_CONFIG_HOME}/bash/aliases/network"
_source "${XDG_CONFIG_HOME}/bash/aliases/pager"
_source "${XDG_CONFIG_HOME}/bash/aliases/posixUtilities"
_source "${XDG_CONFIG_HOME}/bash/aliases/software"
