#!/usr/bin/env bash

_vimless="$(find '/usr/share/vim/'*'/macros/' -name 'less.sh' -print -quit 2>/dev/null)" # [Using Vim like less or more](https://vimhelp.org/various.txt.html#less)

alias less='${_vimless:-less}' # [https://gist.github.com/Gr3yR0n1n/01e00c892dd5b0f12c3e]
