#!/usr/bin/env bash

if [[ -n "${BASH}" ]] && [[ $- == *i* ]];
    then (( "${_VERBOSE}" >= 3 )) && printf '%s\n' "***$(realpath "${BASH_SOURCE[0]}")***";
    else return;
fi

_vimless="$(find '/usr/share/vim/'*'/macros/' -name 'less.sh' -print -quit 2>/dev/null)" # [Using Vim like less or more](https://vimhelp.org/various.txt.html#less)

alias less='${_vimless:-less}' # [https://gist.github.com/Gr3yR0n1n/01e00c892dd5b0f12c3e]
