#!/usr/bin/env bash

log.debug.filepath;

alias tmux='tmux -f "${XDG_CONFIG_HOME}/tmux/tmux.conf"' # [XDG support was reluctantly added for tmux 3.2](https://github.com/tmux/tmux/blob/a5f99e14c6f264e568b860692b89d11f5298a3f2/CHANGES#L145)
# -f file   Specify an alternative configuration file.
